---
# - name: hash -r
#   shell: hash -r

- name: symlink python
  raw: |
    if [ ! -f /usr/bin/python3 ]; then 
      ln --symbolic python3.10 /usr/bin/python3;
    fi
  become: true

- name: symlink python
  raw: |
    if [ ! -f /usr/bin/python ]; then 
      ln --symbolic python3.10 /usr/bin/python;
    fi
  become: true

