---
- name: "Check if file exists"
  stat:
    path: "{{ workbench_full_path }}/{{config_item['target']}}"
  register: file_info

- name: "File exists"
  debug:
    msg: "{{ config_item['target'] }} exists"
  when: file_info.stat.exists

- name: "File does not exist"
  debug:
    msg: "{{ config_item['target'] }} does not exist"
  when: not file_info.stat.exists

- name: Copy file
  copy:
    src: "{{ workbench_full_path }}/{{ config_item['source'] }}"
    dest: "{{ workbench_full_path }}/{{ config_item['target'] }}"
  tags:
    - simple_copy
  when: not file_info.stat.exists