---
- hosts: all
  become: true

  tasks:
    - name: Remove image
      community.docker.docker_image:
        state: absent
        source: local
        name: "{{ docker_nginx_image_name }}"
        tag: latest
    - name: Remove image
      community.docker.docker_image:
        state: absent
        source: local
        name: "{{ docker_nginx_image_name }}"
        tag: "{{ docker_nginx_image_version }}"
    - name: Remove image 2
      community.docker.docker_image:
        state: absent
        source: local
        name: "{{ docker_nginx_image_name_2 }}"
        tag: latest
    - name: Remove image 2
      community.docker.docker_image:
        state: absent
        source: local
        name: "{{ docker_nginx_image_name_2 }}"
        tag: "{{ docker_nginx_image_version_2 }}"
  vars:
    ansible_python_interpreter: /usr/bin/python3.10
