---
- hosts: all
  become: false
  gather_facts: yes
  
  tasks:
    - name: Copy files with rsync
      ansible.posix.synchronize:
        archive: false
        delete: true
        dirs: false
        recursive: true
        group: false
        owner: false
        mode: push
        times: true
        verify_host: true
        private_key: '{{ ansible_ssh_private_key_file }}'
        set_remote_user: true
        src: '{{ workbench_full_path }}/dockerfiles'
        dest: '/home/{{ ansible_user }}'
        dest_port: '{{ ansible_port }}'
        rsync_timeout: 600
