---
- hosts: all
  become: true
  gather_facts: yes

  tasks:
    # - name: hash -r
    #   shell: hash -r

    - name: symlink python
      raw: |
        if [ ! -f /usr/bin/python3 ]; then 
          ln --symbolic python3.10 /usr/bin/python3;
        fi
      become: true

    - name: symlink python
      raw: |
        if [ ! -f /usr/bin/python ]; then 
          ln --symbolic python3.10 /usr/bin/python;
        fi
      become: true

    - name: Install aptitude
      ansible.builtin.apt:
        name: aptitude
        state: latest
        update_cache: true
      become_method: sudo
      become_user: root
      become: true

    - name: Update apt repo and cache
      ansible.builtin.apt: 
        update_cache: yes
        force_apt_get: no
        cache_valid_time: 3600

    - name: Install requests Python package
      ansible.builtin.pip:
        name: requests

    - name: Install required system packages
      ansible.builtin.apt:
        pkg:
          - apt-transport-https 
          - ca-certificates
          - curl
          - software-properties-common
          - gnupg
          - lsb-release
          - lego
        state: latest
        update_cache: true
      become_method: sudo
      become_user: root
      become: true

    - name: Remove docker package
      ansible.builtin.apt:
        name: docker
        state: absent
        update_cache: true
      become_method: sudo
      become_user: root
      become: true

    - name: Remove docker-engine package
      ansible.builtin.apt:
        name: docker-engine
        state: absent
        update_cache: true
      become_method: sudo
      become_user: root
      become: true

    - name: Remove docker.io package
      ansible.builtin.apt:
        name: docker.io
        state: absent
        update_cache: true
      become_method: sudo
      become_user: root
      become: true

    - name: Remove containerd package
      ansible.builtin.apt:
        name: containerd
        state: absent
        update_cache: true
      become_method: sudo
      become_user: root
      become: true

    - name: Remove runc package
      ansible.builtin.apt:
        name: runc
        state: absent
        update_cache: true
      become_method: sudo
      become_user: root
      become: true

    - name: Add Docker GPG apt Key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      become_method: sudo
      become_user: root
      become: true

    - name: Add Docker Repository
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu jammy stable
        state: present
      become_method: sudo
      become_user: root
      become: true

    - name: Install docker-ce
      ansible.builtin.apt:
        name: docker-ce
        state: latest
        update_cache: true
      become_method: sudo
      become_user: root
      become: true

    - name: Install docker-ce-cli
      ansible.builtin.apt:
        name: docker-ce-cli
        state: latest
        update_cache: true
      become_method: sudo
      become_user: root
      become: true

    - name: Install containerd.io
      ansible.builtin.apt:
        name: containerd.io
        state: latest
        update_cache: true
      become_method: sudo
      become_user: root
      become: true

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Ensure group 'docker' exists
      ansible.builtin.group:
        name: docker
        state: present
      become_method: sudo
      become_user: root
      become: true

    - name: Add the user () with a bash shell, appending the group 'docker' to the user's groups
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        shell: /bin/bash
        groups: docker
        append: yes
      become_method: sudo
      become_user: root
      become: true