---
- hosts: all
  become: true
  gather_facts: yes

  tasks:
    - name: Install aptitude
      ansible.builtin.apt:
        name: aptitude
        state: latest
        update_cache: true
      become_method: sudo
      become_user: root
      become: true

    - name: Update apt repo and cache
      ansible.builtin.apt: 
        update_cache: yes
        force_apt_get: no
        cache_valid_time: 3600

    - name: Install required system packages
      ansible.builtin.apt:
        pkg:
          - apt-transport-https 
          - python3-pip
          - ca-certificates
          - curl
          - software-properties-common
          - gnupg
          - lsb-release
          - lego
          - vim
          - git
          - ufw
        state: latest
        update_cache: true
      become_method: sudo
      become_user: root
      become: true

    - name: Install requests Python package
      ansible.builtin.pip:
        name: requests==2.31.0

    - name: UFW - Disable
      community.general.ufw:
        state: disabled
      become_method: sudo
      become_user: root
      become: true

    - name: Allow "{{ ansible_port }}"
      community.general.ufw:
        rule: allow
        port: "{{ ansible_port }}"
      become_method: sudo
      become_user: root
      become: true

    - name: Limit "{{ ansible_port }}"
      community.general.ufw:
        rule: limit
        port: "{{ ansible_port }}"
        proto: tcp
      become_method: sudo
      become_user: root
      become: true

    - name: UFW - Enable
      community.general.ufw:
        state: enabled
      become_method: sudo
      become_user: root
      become: true

    - name: Allow access to tcp port 80
      community.general.ufw:
        rule: allow
        port: "80"
        proto: tcp
      become_method: sudo
      become_user: root
      become: true

    - name: Allow access to tcp port 443
      community.general.ufw:
        rule: allow
        port: "443"
        proto: tcp
      become_method: sudo
      become_user: root
      become: true

    - name: Allow access to tcp port 8080
      community.general.ufw:
        rule: allow
        port: "8080"
        proto: tcp
      become_method: sudo
      become_user: root
      become: true

    - name: Allow access to tcp port 8082
      community.general.ufw:
        rule: allow
        port: "8082"
        proto: tcp
      become_method: sudo
      become_user: root
      become: true

    - name: Enable default deny with logging
      community.general.ufw:
        state: enabled
        default: deny
        logging: "on"
      become_method: sudo
      become_user: root
      become: true

    - name: Remove docker package
      ansible.builtin.apt:
        name: docker
        state: absent
        update_cache: true
      become_method: sudo
      become_user: root
      become: true

    - name: Remove docker-engine package
      ansible.builtin.apt:
        name: docker-engine
        state: absent
        update_cache: true
      become_method: sudo
      become_user: root
      become: true

    - name: Remove docker.io package
      ansible.builtin.apt:
        name: docker.io
        state: absent
        update_cache: true
      become_method: sudo
      become_user: root
      become: true

    - name: Remove containerd package
      ansible.builtin.apt:
        name: containerd
        state: absent
        update_cache: true
      become_method: sudo
      become_user: root
      become: true

    - name: Remove runc package
      ansible.builtin.apt:
        name: runc
        state: absent
        update_cache: true
      become_method: sudo
      become_user: root
      become: true

    - name: Add Docker GPG apt Key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      become_method: sudo
      become_user: root
      become: true

    - name: Add Docker Repository
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu jammy stable
        state: present
      become_method: sudo
      become_user: root
      become: true

    - name: Install docker-ce
      ansible.builtin.apt:
        name: docker-ce
        state: latest
        update_cache: true
      become_method: sudo
      become_user: root
      become: true

    - name: Install docker-ce-cli
      ansible.builtin.apt:
        name: docker-ce-cli
        state: latest
        update_cache: true
      become_method: sudo
      become_user: root
      become: true

    - name: Install containerd.io
      ansible.builtin.apt:
        name: containerd.io
        state: latest
        update_cache: true
      become_method: sudo
      become_user: root
      become: true

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Ensure group docker exists
      ansible.builtin.group:
        name: docker
        state: present
      become_method: sudo
      become_user: root
      become: true

    - name: Add the user () with a bash shell, appending the group docker to the user's groups
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        shell: /bin/bash
        groups: docker
        append: yes
      become_method: sudo
      become_user: root
      become: true