---
- hosts: localhost
  become: false
  gather_facts: yes

  tasks:
    # Install apt packages
    - name: Install packages
      ansible.builtin.apt:
        pkg:
          - python3-pip
          - lego
          - curl
        update_cache: yes
      become: true

    # Install Multipass Snap package
    - name: Install Multipass
      community.general.snap:
        name:
          - multipass
      become: false

    - include_tasks: tasks/copy_resource_as.yml
      loop: "{{resources_to_check}}"
      loop_control:
        loop_var: config_item
      vars:
        resources_to_check:
          - target: "ansible/tasks/dockerrebuild.yml"
            source: "ansible/tasks/dockerrebuild.yml.example"
          - target: "ansible/inventory"
            source: "ansible/inventory.example"
          - target: "dockerfiles/.env"
            source: "dockerfiles/.env.example"
          - target: "dockerfiles/compose.yml"
            source: "dockerfiles/compose.yml.example"
          - target: "dockerfiles/fail2ban/Dockerfile"
            source: "dockerfiles/fail2ban/Dockerfile.example"
          - target: "dockerfiles/fail2ban/jail.local"
            source: "dockerfiles/fail2ban/jail.local.example"
          - target: "dockerfiles/traefik/dynamic.yml"
            source: "dockerfiles/traefik/dynamic.yml.example"
          - target: "dockerfiles/traefik/traefik.yml"
            source: "dockerfiles/traefik/traefik.yml.example"
          - target: "dockerfiles/traefik/Dockerfile"
            source: "dockerfiles/traefik/Dockerfile.example"
          - target: "multipass/cloud-init/cloud-config.yaml"
            source: "multipass/cloud-init/cloud-config.yaml.example"

